name: Continuous Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Java ${{ matrix.java }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
        java:
          - 8
          - 11
        include:
          - os: ubuntu-latest
            java: 11
            coverage: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1

      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: Cache Gradle Modules
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: gradle-caches-${{ hashFiles('**/*.gradle.kts') }}

      - name: Cache Gradle Wrapper
        uses: actions/cache@v1
        with:
          path: ~/.gradle/wrapper
          key: gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}

      - name: Execute Gradle build
        run: ./gradlew build ${{ matrix.coverage && 'jacocoTestReport' || '' }} --stacktrace
        shell: bash

      - uses: codecov/codecov-action@v1
        if: ${{ matrix.coverage }}
        with:
          files: ./aws-xray-agent/build/reports/jacoco/test/jacocoTestReport.xml

      - uses: actions/upload-artifact@v2
        if: ${{ matrix.coverage }}
        with:
          name: coverage-report
          path: ./aws-xray-agent/build/reports/jacoco/test/html
