name: Continuous Build
on: [push, pull_request]

jobs:
  build:
    name: Build Java ${{ matrix.java }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
        java:
          - 8
          - 11
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Cache Gradle Modules
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: gradle-caches-${{ hashFiles('**/*.gradle.kts') }}
      - name: Cache Gradle Wrapper
        uses: actions/cache@v1
        with:
          path: ~/.gradle/wrapper
          key: gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
      - name: Execute Gradle build
        run: ./gradlew build --stacktrace
        shell: bash
